export const COURSES = [
  {
    course_id: "cs101",
    title: "Introduction to Computer Science",
    domain: "computer_science",
    level: "beginner",
    duration_hours: 40,
    description: "Fundamental concepts of CS including algorithms, data structures, and computational thinking.",
    skills_taught: ["programming_basics", "computational_thinking", "problem_solving"],
    rating: 4.7,
    enrolled: 150000,
    provider: "edX",
  },
  {
    course_id: "python101",
    title: "Python for Everybody",
    domain: "programming",
    level: "beginner",
    duration_hours: 30,
    description: "Learn to program and analyze data using Python. Variables, conditionals, loops, functions, data structures.",
    skills_taught: ["python", "basic_programming", "data_structures"],
    rating: 4.8,
    enrolled: 200000,
    provider: "Coursera",
  },
  {
    course_id: "webdev101",
    title: "HTML CSS JavaScript for Web Developers",
    domain: "web_development",
    level: "beginner",
    duration_hours: 35,
    description: "Build modern web pages using HTML5 CSS3 and JavaScript. Responsive design and web standards.",
    skills_taught: ["html", "css", "javascript", "responsive_design"],
    rating: 4.6,
    enrolled: 120000,
    provider: "Coursera",
  },
  {
    course_id: "datascience101",
    title: "Introduction to Data Science",
    domain: "data_science",
    level: "beginner",
    duration_hours: 45,
    description: "Explore data science: data collection analysis visualization and basic statistics.",
    skills_taught: ["data_analysis", "statistics", "data_visualization", "critical_thinking"],
    rating: 4.5,
    enrolled: 95000,
    provider: "edX",
  },
  {
    course_id: "python201",
    title: "Intermediate Python Programming",
    domain: "programming",
    level: "intermediate",
    duration_hours: 25,
    description: "Deepen Python skills: OOP decorators generators context managers advanced data structures.",
    skills_taught: ["python_advanced", "oop", "decorators", "context_managers"],
    rating: 4.6,
    enrolled: 80000,
    provider: "Coursera",
  },
  {
    course_id: "algorithms201",
    title: "Algorithms Specialization",
    domain: "computer_science",
    level: "intermediate",
    duration_hours: 60,
    description: "Divide-and-conquer sorting graph algorithms dynamic programming greedy algorithms.",
    skills_taught: ["algorithms", "dynamic_programming", "graph_theory", "complexity_analysis"],
    rating: 4.7,
    enrolled: 75000,
    provider: "Coursera",
  },
  {
    course_id: "react201",
    title: "Meta React Developer Certificate",
    domain: "web_development",
    level: "intermediate",
    duration_hours: 80,
    description: "Build dynamic web apps with React. Hooks state management routing testing.",
    skills_taught: ["react", "javascript_advanced", "state_management", "testing"],
    rating: 4.7,
    enrolled: 110000,
    provider: "Coursera",
  },
  {
    course_id: "ml201",
    title: "Machine Learning by Andrew Ng",
    domain: "machine_learning",
    level: "intermediate",
    duration_hours: 55,
    description: "Classic ML: supervised learning unsupervised learning best practices neural networks.",
    skills_taught: ["machine_learning", "linear_regression", "neural_networks", "model_evaluation"],
    rating: 4.9,
    enrolled: 300000,
    provider: "Coursera",
  },
  {
    course_id: "ds201",
    title: "Applied Data Science with Python",
    domain: "data_science",
    level: "intermediate",
    duration_hours: 50,
    description: "Hands-on data science: pandas NumPy matplotlib scikit-learn NLP basics.",
    skills_taught: ["pandas", "numpy", "matplotlib", "scikit_learn", "nlp_basics"],
    rating: 4.6,
    enrolled: 88000,
    provider: "Coursera",
  },
  {
    course_id: "nodejs201",
    title: "Server-side Development with NodeJS",
    domain: "web_development",
    level: "intermediate",
    duration_hours: 35,
    description: "Scalable server-side apps with Node.js Express MongoDB REST APIs.",
    skills_taught: ["nodejs", "express", "mongodb", "rest_api"],
    rating: 4.5,
    enrolled: 70000,
    provider: "Coursera",
  },
  {
    course_id: "db201",
    title: "Database Design and Basic SQL",
    domain: "data_management",
    level: "beginner",
    duration_hours: 20,
    description: "Relational database design normalization SQL queries joins subqueries indexes.",
    skills_taught: ["sql", "database_design", "normalization", "query_optimization"],
    rating: 4.4,
    enrolled: 65000,
    provider: "Coursera",
  },
  {
    course_id: "dl301",
    title: "Deep Learning Specialization",
    domain: "machine_learning",
    level: "advanced",
    duration_hours: 90,
    description: "CNNs RNNs LSTMs transformers GANs practical implementations.",
    skills_taught: ["deep_learning", "cnn", "rnn", "transformers", "gan"],
    rating: 4.9,
    enrolled: 250000,
    provider: "Coursera",
  },
  {
    course_id: "nlp301",
    title: "NLP Specialization",
    domain: "machine_learning",
    level: "advanced",
    duration_hours: 70,
    description: "Sentiment analysis machine translation transformers question answering.",
    skills_taught: ["nlp", "text_processing", "transformers", "sentiment_analysis"],
    rating: 4.7,
    enrolled: 60000,
    provider: "Coursera",
  },
  {
    course_id: "cloud301",
    title: "AWS Cloud Practitioner",
    domain: "cloud_computing",
    level: "beginner",
    duration_hours: 25,
    description: "AWS cloud concepts core services security pricing support.",
    skills_taught: ["cloud_basics", "aws", "deployment", "security_basics"],
    rating: 4.6,
    enrolled: 100000,
    provider: "Coursera",
  },
  {
    course_id: "devops301",
    title: "DevOps on AWS",
    domain: "cloud_computing",
    level: "intermediate",
    duration_hours: 65,
    description: "CI/CD infrastructure as code Docker Kubernetes on AWS.",
    skills_taught: ["devops", "docker", "kubernetes", "ci_cd", "terraform"],
    rating: 4.5,
    enrolled: 55000,
    provider: "Coursera",
  },
  {
    course_id: "cybersec101",
    title: "Introduction to Cybersecurity",
    domain: "cybersecurity",
    level: "beginner",
    duration_hours: 30,
    description: "Network security cryptography security frameworks.",
    skills_taught: ["network_security", "cryptography", "security_frameworks"],
    rating: 4.4,
    enrolled: 80000,
    provider: "Coursera",
  },
  {
    course_id: "mobile101",
    title: "Flutter Mobile Development",
    domain: "mobile_development",
    level: "intermediate",
    duration_hours: 50,
    description: "Build mobile apps with Flutter and Dart. Widgets state management deployment.",
    skills_taught: ["flutter", "dart", "mobile_development", "ui_design"],
    rating: 4.6,
    enrolled: 45000,
    provider: "Coursera",
  },
  {
    course_id: "aiml301",
    title: "AI for Everyone",
    domain: "artificial_intelligence",
    level: "beginner",
    duration_hours: 20,
    description: "Non-technical AI intro: concepts capabilities limitations implications.",
    skills_taught: ["ai_literacy", "ai_strategy", "ethics", "business_ai"],
    rating: 4.8,
    enrolled: 500000,
    provider: "Coursera",
  },
  {
    course_id: "dp401",
    title: "MLOps Specialization",
    domain: "machine_learning",
    level: "advanced",
    duration_hours: 75,
    description: "End-to-end ML pipeline: data engineering model development deployment monitoring.",
    skills_taught: ["mlops", "model_deployment", "feature_engineering", "model_monitoring"],
    rating: 4.7,
    enrolled: 35000,
    provider: "Coursera",
  },
  {
    course_id: "fullstack401",
    title: "Full Stack Capstone Project",
    domain: "web_development",
    level: "advanced",
    duration_hours: 60,
    description: "Complete full-stack app: frontend backend database auth deployment.",
    skills_taught: ["full_stack", "system_design", "authentication", "deployment"],
    rating: 4.6,
    enrolled: 40000,
    provider: "Coursera",
  },
];

export const SKILLS = {
  python: { category: "programming", level: "beginner", related: ["python_advanced", "data_structures", "basic_programming"], demand_score: 0.95 },
  python_advanced: { category: "programming", level: "intermediate", related: ["python", "oop", "decorators"], demand_score: 0.9 },
  javascript: { category: "web", level: "beginner", related: ["html", "css", "react", "nodejs"], demand_score: 0.93 },
  javascript_advanced: { category: "web", level: "intermediate", related: ["javascript", "react", "state_management"], demand_score: 0.88 },
  html: { category: "web", level: "beginner", related: ["css", "javascript", "responsive_design"], demand_score: 0.85 },
  css: { category: "web", level: "beginner", related: ["html", "javascript", "responsive_design"], demand_score: 0.82 },
  react: { category: "web", level: "intermediate", related: ["javascript", "state_management", "testing"], demand_score: 0.91 },
  nodejs: { category: "web", level: "intermediate", related: ["express", "mongodb", "rest_api"], demand_score: 0.87 },
  express: { category: "web", level: "intermediate", related: ["nodejs", "mongodb", "rest_api"], demand_score: 0.84 },
  machine_learning: { category: "ai", level: "intermediate", related: ["linear_regression", "neural_networks", "model_evaluation"], demand_score: 0.94 },
  deep_learning: { category: "ai", level: "advanced", related: ["cnn", "rnn", "transformers", "neural_networks"], demand_score: 0.92 },
  nlp: { category: "ai", level: "advanced", related: ["text_processing", "transformers", "sentiment_analysis"], demand_score: 0.89 },
  data_analysis: { category: "data", level: "beginner", related: ["statistics", "data_visualization", "pandas"], demand_score: 0.88 },
  statistics: { category: "data", level: "beginner", related: ["data_analysis", "machine_learning", "probability"], demand_score: 0.86 },
  pandas: { category: "data", level: "intermediate", related: ["numpy", "matplotlib", "data_analysis"], demand_score: 0.87 },
  numpy: { category: "data", level: "intermediate", related: ["pandas", "matplotlib", "scikit_learn"], demand_score: 0.85 },
  sql: { category: "data", level: "beginner", related: ["database_design", "normalization", "query_optimization"], demand_score: 0.9 },
  docker: { category: "devops", level: "intermediate", related: ["kubernetes", "ci_cd", "terraform"], demand_score: 0.88 },
  kubernetes: { category: "devops", level: "advanced", related: ["docker", "ci_cd", "terraform"], demand_score: 0.86 },
  aws: { category: "cloud", level: "beginner", related: ["cloud_basics", "deployment", "security_basics"], demand_score: 0.92 },
  cloud_basics: { category: "cloud", level: "beginner", related: ["aws", "deployment", "security_basics"], demand_score: 0.85 },
  network_security: { category: "security", level: "beginner", related: ["cryptography", "security_frameworks"], demand_score: 0.83 },
  flutter: { category: "mobile", level: "intermediate", related: ["dart", "mobile_development", "ui_design"], demand_score: 0.84 },
  git: { category: "tools", level: "beginner", related: ["linux", "ci_cd"], demand_score: 0.9 },
  linux: { category: "tools", level: "beginner", related: ["git", "docker", "devops"], demand_score: 0.82 },
  ai_literacy: { category: "ai", level: "beginner", related: ["ai_strategy", "ethics", "business_ai"], demand_score: 0.88 },
  mlops: { category: "ai", level: "advanced", related: ["model_deployment", "feature_engineering", "model_monitoring"], demand_score: 0.87 },
  responsive_design: { category: "web", level: "beginner", related: ["html", "css", "javascript"], demand_score: 0.8 },
  state_management: { category: "web", level: "intermediate", related: ["react", "javascript_advanced"], demand_score: 0.83 },
  testing: { category: "tools", level: "intermediate", related: ["react", "javascript_advanced"], demand_score: 0.85 },
  rest_api: { category: "web", level: "intermediate", related: ["nodejs", "express", "mongodb"], demand_score: 0.86 },
  mongodb: { category: "data", level: "intermediate", related: ["nodejs", "express", "rest_api"], demand_score: 0.82 },
  linear_regression: { category: "ai", level: "intermediate", related: ["machine_learning", "model_evaluation", "statistics"], demand_score: 0.84 },
  neural_networks: { category: "ai", level: "intermediate", related: ["machine_learning", "deep_learning", "cnn"], demand_score: 0.9 },
  model_evaluation: { category: "ai", level: "intermediate", related: ["machine_learning", "linear_regression"], demand_score: 0.85 },
  transformers: { category: "ai", level: "advanced", related: ["nlp", "deep_learning", "text_processing"], demand_score: 0.91 },
  cnn: { category: "ai", level: "advanced", related: ["deep_learning", "neural_networks"], demand_score: 0.88 },
  rnn: { category: "ai", level: "advanced", related: ["deep_learning", "neural_networks", "nlp"], demand_score: 0.85 },
  matplotlib: { category: "data", level: "intermediate", related: ["pandas", "numpy", "data_visualization"], demand_score: 0.83 },
  scikit_learn: { category: "ai", level: "intermediate", related: ["machine_learning", "pandas", "numpy"], demand_score: 0.87 },
  database_design: { category: "data", level: "beginner", related: ["sql", "normalization", "query_optimization"], demand_score: 0.84 },
  normalization: { category: "data", level: "beginner", related: ["database_design", "sql"], demand_score: 0.78 },
  query_optimization: { category: "data", level: "intermediate", related: ["sql", "database_design"], demand_score: 0.82 },
  ci_cd: { category: "devops", level: "intermediate", related: ["docker", "kubernetes", "terraform"], demand_score: 0.86 },
  terraform: { category: "devops", level: "advanced", related: ["docker", "kubernetes", "ci_cd"], demand_score: 0.84 },
  devops: { category: "devops", level: "intermediate", related: ["docker", "kubernetes", "ci_cd"], demand_score: 0.87 },
  deployment: { category: "devops", level: "intermediate", related: ["aws", "docker", "ci_cd"], demand_score: 0.85 },
  security_basics: { category: "security", level: "beginner", related: ["network_security", "cryptography"], demand_score: 0.8 },
  cryptography: { category: "security", level: "intermediate", related: ["network_security", "security_frameworks"], demand_score: 0.83 },
  security_frameworks: { category: "security", level: "intermediate", related: ["network_security", "cryptography"], demand_score: 0.81 },
  mobile_development: { category: "mobile", level: "intermediate", related: ["flutter", "dart", "ui_design"], demand_score: 0.86 },
  dart: { category: "mobile", level: "intermediate", related: ["flutter", "mobile_development"], demand_score: 0.79 },
  ui_design: { category: "design", level: "beginner", related: ["responsive_design", "html", "css"], demand_score: 0.81 },
  ai_strategy: { category: "ai", level: "beginner", related: ["ai_literacy", "business_ai"], demand_score: 0.85 },
  ethics: { category: "ai", level: "beginner", related: ["ai_literacy", "ai_strategy"], demand_score: 0.75 },
  business_ai: { category: "ai", level: "beginner", related: ["ai_literacy", "ai_strategy"], demand_score: 0.83 },
  model_deployment: { category: "ai", level: "advanced", related: ["mlops", "feature_engineering"], demand_score: 0.88 },
  feature_engineering: { category: "ai", level: "advanced", related: ["mlops", "model_deployment", "machine_learning"], demand_score: 0.86 },
  model_monitoring: { category: "ai", level: "advanced", related: ["mlops", "model_deployment"], demand_score: 0.82 },
  full_stack: { category: "web", level: "advanced", related: ["system_design", "authentication", "deployment"], demand_score: 0.9 },
  system_design: { category: "engineering", level: "advanced", related: ["full_stack", "algorithms"], demand_score: 0.89 },
  authentication: { category: "security", level: "intermediate", related: ["rest_api", "security_basics"], demand_score: 0.84 },
  programming_basics: { category: "programming", level: "beginner", related: ["python", "basic_programming"], demand_score: 0.92 },
  computational_thinking: { category: "programming", level: "beginner", related: ["problem_solving", "algorithms"], demand_score: 0.85 },
  problem_solving: { category: "programming", level: "beginner", related: ["algorithms", "computational_thinking"], demand_score: 0.9 },
  basic_programming: { category: "programming", level: "beginner", related: ["python", "programming_basics"], demand_score: 0.91 },
  data_structures: { category: "programming", level: "beginner", related: ["algorithms", "python"], demand_score: 0.88 },
  algorithms: { category: "programming", level: "intermediate", related: ["data_structures", "dynamic_programming", "graph_theory"], demand_score: 0.89 },
  dynamic_programming: { category: "programming", level: "intermediate", related: ["algorithms", "graph_theory"], demand_score: 0.85 },
  graph_theory: { category: "programming", level: "intermediate", related: ["algorithms", "dynamic_programming"], demand_score: 0.82 },
  complexity_analysis: { category: "programming", level: "intermediate", related: ["algorithms", "data_structures"], demand_score: 0.83 },
  data_visualization: { category: "data", level: "beginner", related: ["matplotlib", "data_analysis", "statistics"], demand_score: 0.84 },
  critical_thinking: { category: "soft_skills", level: "beginner", related: ["problem_solving"], demand_score: 0.8 },
  text_processing: { category: "ai", level: "advanced", related: ["nlp", "transformers"], demand_score: 0.84 },
  sentiment_analysis: { category: "ai", level: "intermediate", related: ["nlp", "text_processing"], demand_score: 0.81 },
  gan: { category: "ai", level: "advanced", related: ["deep_learning", "neural_networks"], demand_score: 0.83 },
  oop: { category: "programming", level: "intermediate", related: ["python_advanced", "decorators"], demand_score: 0.87 },
  decorators: { category: "programming", level: "intermediate", related: ["python_advanced", "oop"], demand_score: 0.78 },
  context_managers: { category: "programming", level: "intermediate", related: ["python_advanced"], demand_score: 0.75 },
};

export const CAREER_PATHS = {
  data_scientist: {
    display_name: "Data Scientist",
    required_skills: ["python", "statistics", "machine_learning", "data_analysis", "data_visualization", "pandas", "numpy", "sql"],
    nice_to_have: ["deep_learning", "nlp", "scikit_learn", "matplotlib"],
    description: "Analyze complex data sets to extract insights and build predictive models.",
    avg_salary: "$120,000",
    growth_rate: "36%",
  },
  ml_engineer: {
    display_name: "ML Engineer",
    required_skills: ["python", "machine_learning", "deep_learning", "model_evaluation", "neural_networks", "transformers"],
    nice_to_have: ["mlops", "model_deployment", "docker", "cloud_basics"],
    description: "Design and deploy machine learning systems at scale.",
    avg_salary: "$130,000",
    growth_rate: "40%",
  },
  full_stack_developer: {
    display_name: "Full Stack Developer",
    required_skills: ["html", "css", "javascript", "react", "nodejs", "express", "mongodb", "rest_api", "sql"],
    nice_to_have: ["docker", "git", "testing", "authentication"],
    description: "Build complete web applications from frontend to backend.",
    avg_salary: "$105,000",
    growth_rate: "25%",
  },
  frontend_developer: {
    display_name: "Frontend Developer",
    required_skills: ["html", "css", "javascript", "react", "responsive_design", "state_management"],
    nice_to_have: ["testing", "ui_design"],
    description: "Build user interfaces and interactive web experiences.",
    avg_salary: "$95,000",
    growth_rate: "22%",
  },
  backend_developer: {
    display_name: "Backend Developer",
    required_skills: ["python", "nodejs", "express", "sql", "mongodb", "rest_api", "database_design"],
    nice_to_have: ["docker", "aws", "ci_cd", "authentication"],
    description: "Build server-side logic, APIs, and database systems.",
    avg_salary: "$110,000",
    growth_rate: "28%",
  },
  cloud_engineer: {
    display_name: "Cloud Engineer",
    required_skills: ["aws", "cloud_basics", "docker", "kubernetes", "ci_cd", "terraform", "devops"],
    nice_to_have: ["python", "linux", "security_basics"],
    description: "Design and manage cloud infrastructure and deployments.",
    avg_salary: "$125,000",
    growth_rate: "35%",
  },
  data_analyst: {
    display_name: "Data Analyst",
    required_skills: ["sql", "data_analysis", "statistics", "data_visualization", "pandas", "matplotlib"],
    nice_to_have: ["python", "excel", "tableau"],
    description: "Transform raw data into actionable business insights.",
    avg_salary: "$85,000",
    growth_rate: "25%",
  },
  devops_engineer: {
    display_name: "DevOps Engineer",
    required_skills: ["docker", "kubernetes", "ci_cd", "terraform", "aws", "linux", "git"],
    nice_to_have: ["python", "monitoring", "security_basics"],
    description: "Automate and streamline software delivery and infrastructure.",
    avg_salary: "$120,000",
    growth_rate: "32%",
  },
  mobile_developer: {
    display_name: "Mobile Developer",
    required_skills: ["flutter", "dart", "mobile_development", "ui_design", "rest_api"],
    nice_to_have: ["sql", "authentication", "testing"],
    description: "Build mobile applications for iOS and Android.",
    avg_salary: "$100,000",
    growth_rate: "22%",
  },
  cybersecurity_analyst: {
    display_name: "Cybersecurity Analyst",
    required_skills: ["network_security", "cryptography", "security_frameworks", "linux"],
    nice_to_have: ["python", "cloud_basics", "security_basics"],
    description: "Protect organizations from cyber threats and vulnerabilities.",
    avg_salary: "$100,000",
    growth_rate: "33%",
  },
  ai_product_manager: {
    display_name: "AI Product Manager",
    required_skills: ["ai_literacy", "ai_strategy", "business_ai", "ethics"],
    nice_to_have: ["machine_learning", "data_analysis", "statistics"],
    description: "Lead AI-powered product development and strategy.",
    avg_salary: "$140,000",
    growth_rate: "30%",
  },
  software_engineer: {
    display_name: "Software Engineer",
    required_skills: ["python", "programming_basics", "algorithms", "data_structures", "git", "linux"],
    nice_to_have: ["sql", "docker", "testing"],
    description: "Design, build, and maintain software systems.",
    avg_salary: "$115,000",
    growth_rate: "25%",
  },
};

export const PREREQUISITES = {
  python201: ["python101"],
  algorithms201: ["python101", "cs101"],
  react201: ["webdev101"],
  ml201: ["python101", "datascience101"],
  ds201: ["datascience101", "python101"],
  nodejs201: ["webdev101"],
  dl301: ["ml201", "python201"],
  nlp301: ["ml201", "python201"],
  devops301: ["cloud301"],
  mobile101: ["python101"],
  dp401: ["ml201", "cloud301", "python201"],
  fullstack401: ["react201", "nodejs201", "db201"],
  datascience101: ["python101"],
  db201: [],
  cs101: [],
  python101: [],
  webdev101: [],
  cloud301: [],
  cybersec101: [],
  aiml301: [],
};

export const COURSE_TO_SKILLS = {
  cs101: ["programming_basics", "computational_thinking", "problem_solving"],
  python101: ["python", "basic_programming", "data_structures"],
  webdev101: ["html", "css", "javascript", "responsive_design"],
  datascience101: ["data_analysis", "statistics", "data_visualization", "critical_thinking"],
  python201: ["python_advanced", "oop", "decorators", "context_managers"],
  algorithms201: ["algorithms", "dynamic_programming", "graph_theory", "complexity_analysis"],
  react201: ["react", "javascript_advanced", "state_management", "testing"],
  ml201: ["machine_learning", "linear_regression", "neural_networks", "model_evaluation"],
  ds201: ["pandas", "numpy", "matplotlib", "scikit_learn", "nlp_basics"],
  nodejs201: ["nodejs", "express", "mongodb", "rest_api"],
  db201: ["sql", "database_design", "normalization", "query_optimization"],
  dl301: ["deep_learning", "cnn", "rnn", "transformers", "gan"],
  nlp301: ["nlp", "text_processing", "transformers", "sentiment_analysis"],
  cloud301: ["cloud_basics", "aws", "deployment", "security_basics"],
  devops301: ["devops", "docker", "kubernetes", "ci_cd", "terraform"],
  cybersec101: ["network_security", "cryptography", "security_frameworks"],
  mobile101: ["flutter", "dart", "mobile_development", "ui_design"],
  aiml301: ["ai_literacy", "ai_strategy", "ethics", "business_ai"],
  dp401: ["mlops", "model_deployment", "feature_engineering", "model_monitoring"],
  fullstack401: ["full_stack", "system_design", "authentication", "deployment"],
};
